# general settings
name: train_HFUR_qp32
model_type: HFURModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: LDV  
    type: LDVDataset
    dataroot_gt: /home/zqy/dataset/train_gt   
    dataroot_lq: /home/zqy/dataset/train_qp32
    dataroot_flow: ~
    meta_info_file: /home/zqy/EDVR-master/basicsr/data/meta_info/meta_info_LDV_GTQP.txt  
    val_partition: LDV  
    io_backend:
      type: disk

    num_frame: 5 
    gt_size: 64
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1000
    prefetch_mode: ~

  val:
    name: LDV
    type: VideoTestDataset
    dataroot_gt: 
    dataroot_lq: 
    meta_info_file: 
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5
    padding: reflection_circle

# network structures
network_g:
  type: HFUR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: true

# path
path:
  root: /home/zqy/HFUR
  pretrain_network_g: 
  strict_load_g: False
  resume_state: 
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 150000, 150000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

    

  total_iter: 300000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 0.01

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: False

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
